algoritmo diaria
    caractere dias_semanas
       inicio
    escolha("dias"){
        caso 5:
        instrucoes
           escreva ("quarto simples, valor da diaria R$ 100,00")
           pare
        caso s:
        instrucoes
            escrev ("quarto duplo, valor da diaria R$ 150,00")
            pare
        caso i:
        instrucoes
            escreva ("quarto triplo, valor da diaria R$ 200,00")
            pare 

            fim
        }
    fim
