algoritmo aula6
      inteiro opc
      inicio
      escolha(opc){
            caso 1:
                  escreva("vc escolheu opção 1")
                  pare
            caso 2:
                  escreva("vc escolheu opção 2")
                  pare
            caso 3:
                  escreva("vc escolheu opção 3")
                  pare
            outrocaso:
                  escreva("opção inválida")
      } 